# www.kr.freebsd.org site build
# build only; deployment need to be manually done.
name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.134.3'
          extended: true

      - name: Hugo build
        run: hugo --logLevel info --minify -e production

      - name: Deploy to www.kr.freebsd.org
        uses: up9cloud/action-rsync@master
        env:
          MODE: push
          HOST: www.kr.freebsd.org
          USER: ${{ secrets.WWW_USER }}
          KEY: ${{ secrets.WWW_SSHKEY }}
          VERBOSE: true
          SOURCE: public/
          TARGET: /kfug/sites/wwwpub/www.kr.freebsd.org
