#
# www.kr.freebsd.org site build: for every push,
# run hugo to verify.
#
name: Check

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true

      - name: Hugo build
        run: hugo --logLevel debug --minify
